pipeline {
    agent any

    parameters {
        choice(
            name: 'ENV',
            choices: ['dev', 'prod'],
            description: 'Select environment to deploy'
        )

        booleanParam(
            name: 'AUTO_APPLY',
            defaultValue: false,
            description: 'If true, Terraform apply will run automatically'
        )

        booleanParam(
            name: 'AUTO_DESTROY',
            defaultValue: false,
            description: '⚠️ DESTROY all Terraform-managed infrastructure'
        )
    }

    options {
        timestamps()
    }

    environment {
        TF_IN_AUTOMATION = "true"
    }

    stages {

        stage('Terraform Init') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-creds',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    dir("envs/${params.ENV}") {
                        bat 'terraform init -reconfigure -input=false'
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir("envs/${params.ENV}") {
                    bat 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-creds',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    dir("envs/${params.ENV}") {
                        bat 'terraform plan -var-file=terraform.tfvars -out=tfplan -input=false'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            when {
                expression { params.AUTO_APPLY && !params.AUTO_DESTROY }
            }
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-creds',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    dir("envs/${params.ENV}") {
                        bat 'terraform apply -auto-approve tfplan'
                    }
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { params.AUTO_DESTROY && !params.AUTO_APPLY }
            }
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-creds',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    dir("envs/${params.ENV}") {
                        bat 'terraform destroy -var-file=terraform.tfvars -auto-approve'
                    }
                }
            }
        }
    }
}
